name: Feature Request
description: Suggest a new feature or enhancement for the Blazor Furniture App
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.
  
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: Briefly describe the feature...
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: e.g., I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Any alternative approaches you've thought about...
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial.
      placeholder: |
        1. Use case 1...
        2. Use case 2...
  
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, sketches, or examples from other applications.
      placeholder: Paste or drag images here, or provide links to examples...
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request.
      placeholder: Any additional information that might be helpful...
